<a href="https://colab.research.google.com/github/Deval2211/Movies-Recommendation/blob/master/Movies_Recommendation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
!curl -L -O https://raw.githubusercontent.com/Deval2211/Movies-Recommendation/master/Dataset/final_dataset.csv

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 44.7M  100 44.7M    0     0  45.4M      0 --:--:-- --:--:-- --:--:-- 45.4M

In [12]:
import pandas as pd

In [14]:
df = pd.read_csv("/content/final_dataset.csv")
df.head()

,id,title,duration,MPA,rating,votes,meta_score,description,movie_link,writers,...,opening_weekend_gross,gross_worldwide,gross_us_canada,release_date,countries_origin,filming_locations,production_companies,awards_content,genres,languages
0,tt10208198,"The Gangster, the Cop, the Devil",1h 49m,Not Rated,7.0,28K,65.0,A crime boss teams up with a cop to track down...,https://www.imdb.com/title/tt10208198/,['Lee Won-tae'],...,"$78,655","$25,775,371","$216,494",2019-05-15,['South Korea'],"['Seoul, South Korea']","['Kiwi Media Group', 'Acemaker Movieworks', 'B...","Awards, 1 win & 2 nominations total","['True Crime', 'Action', 'Crime', 'Thriller']","['Korean', 'English']"
1,tt3960412,Popstar: Never Stop Never Stopping,1h 27m,R,6.7,71K,68.0,When it becomes clear that his solo album is a...,https://www.imdb.com/title/tt3960412/,"['Andy Samberg', 'Akiva Schaffer', 'Jorma Tacc...",...,"$4,698,715","$9,680,029","$9,639,125",2016-06-03,"['United States', 'China']",NaN,"['Universal Pictures', 'Perfect World Pictures...","Awards, 1 win & 6 nominations total","['Mockumentary', 'Raunchy Comedy', 'Comedy', '...",['English']
2,tt1001508,He's Just Not That Into You,2h 9m,PG-13,6.4,188K,47.0,This Baltimore-set movie of interconnecting st...,https://www.imdb.com/title/tt1001508/,"['Abby Kohn', 'Marc Silverstein', 'Greg Behren...",...,"$27,785,487","$178,866,158","$93,953,653",2009-02-06,"['Germany', 'United States']","['Handy Market - 2514 W. Magnolia Boulevard, B...","['New Line Cinema', 'Flower Films (II)', 'Inte...","Awards, 1 win & 4 nominations total","['Feel-Good Romance', 'Romantic Comedy', 'Come...",['English']
3,tt0038303,Anna and the King of Siam,2h 8m,Approved,7.0,2.8K,NaN,"In 1862, a young Englishwoman becomes royal tu...",https://www.imdb.com/title/tt0038303/,"['Talbot Jennings', 'Sally Benson', 'Margaret ...",...,NaN,NaN,NaN,1946-09-06,['United States'],['Los Angeles County Arboretum & Botanic Garde...,['Twentieth Century Fox'],"Won 2 Oscars, 6 wins & 6 nominations total","['Period Drama', 'Biography', 'Drama', 'Romance']",['English']
4,tt1401152,Unknown,1h 53m,PG-13,6.8,273K,56.0,When a man awakens from a coma only to discove...,https://www.imdb.com/title/tt1401152/,"['Oliver Butcher', 'Stephen Cornwell', 'Didier...",...,"$21,856,389","$135,710,029","$63,686,397",2011-02-18,"['United States', 'Germany', 'United Kingdom',...","['Tresor, Berlin, Germany (night club scene)']","['Dark Castle Entertainment', 'Panda Productio...","Awards, 3 nominations total","['Action', 'Mystery', 'Thriller']","['English', 'German', 'Turkish', 'Arabic']"